import { AnimationMetadataType } from "./AnimationMetadataType";

export const emotions: {
  [key: string]: {
    sentiment: number;
  };
} = {
  love: { sentiment: 1.0 },
  joy: { sentiment: 0.97 },
  gratitude: { sentiment: 0.94 },
  caring: { sentiment: 0.91 },
  excitement: { sentiment: 0.88 },
  admiration: { sentiment: 0.85 },
  optimism: { sentiment: 0.82 },
  pride: { sentiment: 0.79 },
  amusement: { sentiment: 0.76 },
  relief: { sentiment: 0.73 },
  approval: { sentiment: 0.7 },
  desire: { sentiment: 0.67 },
  curiosity: { sentiment: 0.64 },
  surprise: { sentiment: 0.61 },
  realization: { sentiment: 0.58 },
  neutral: { sentiment: 0.55 },
  confusion: { sentiment: 0.52 },
  embarrassment: { sentiment: 0.49 },
  nervousness: { sentiment: 0.46 },
  annoyance: { sentiment: 0.43 },
  disapproval: { sentiment: 0.4 },
  remorse: { sentiment: 0.37 },
  fear: { sentiment: 0.34 },
  disappointment: { sentiment: 0.31 },
  sadness: { sentiment: 0.28 },
  anger: { sentiment: 0.25 },
  grief: { sentiment: 0.22 },
  disgust: { sentiment: 0.19 },
} as const;

export interface EmotionAnimationMetadataType extends AnimationMetadataType {
  metaType: "motion";
  name: string;
  url: string;
  motion: string;
  motionType: "Gesture" | "Loop";
  motionSituation: "formal" | "informal";
  onlyWhileTalking: boolean;
  useAsFallback: boolean;
  type: "bvh" | "fbx" | "vrma";
}

export const emotionAnimations: {
  [emotion: string]: {
    [intensity: number]: EmotionAnimationMetadataType[];
  };
} = {
  love: {},
  caring: {},
  admiration: {},
  amusement: {},
  realization: {},
  nervousness: {},
  disgust: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "disgust",
        key: "disgust",
        useAsFallback: true,
        name: "Slouched Posture",
        url: "aic-runtime-deps/animations/emotions/Orc_Idle.fbx",
        motion: "Slightly slouched posture with tense hands",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  desire: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "desire",
        key: "desire",
        useAsFallback: false,
        name: "Emoted Talking",
        url: "aic-runtime-deps/animations/emotions/Emoted_Talking.fbx",
        motion:
          "Talking with hand gestures in a confident manner with a certain 'desire' that I cannot quite describe",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  optimism: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "optimism",
        key: "optimism",
        useAsFallback: true,
        name: "Chest Out Posture",
        url: "aic-runtime-deps/animations/emotions/Neutral_Idle.fbx",
        motion: "Stading confidently with the chest out",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "optimism",
        key: "optimism",
        useAsFallback: false,
        name: "Fist Hit",
        url: "aic-runtime-deps/animations/emotions/Standing_Cheering.fbx",
        motion:
          "Flat fist hit at chest height, kind of like hitting an imaginary table",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  grief: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "grief",
        key: "grief",
        useAsFallback: true,
        name: "Slumped Stance",
        url: "aic-runtime-deps/animations/emotions/Neutral_Idle.fbx",
        motion: "Standing with a slightly weak posture",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "grief",
        key: "grief",
        useAsFallback: true,
        name: "Slumped Swaying",
        url: "aic-runtime-deps/animations/emotions/Injured_Idle.fbx",
        motion: "Swaying forward and backward while leaning forward",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  surprise: {
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "surprise",
        key: "surprise",
        useAsFallback: true,
        name: "Surprised Backstep",
        url: "aic-runtime-deps/animations/emotions/Focus.fbx",
        motion: "Stepping back and tumbling slightly with wide arms",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "surprise",
        key: "surprise",
        useAsFallback: true,
        name: "Excited Stance",
        url: "aic-runtime-deps/animations/emotions/Getting_Up_End.fbx",
        motion: "Arms wide to the sides while in a wide stance",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "surprise",
        key: "surprise",
        useAsFallback: true,
        name: "Shocked",
        url: "aic-runtime-deps/animations/emotions/Standing_Block_Start.fbx",
        motion: "Hands forward at chest height with angled knees and elbows",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  relief: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "relief",
        key: "relief",
        useAsFallback: false,
        name: "Relieved Sigh",
        url: "aic-runtime-deps/animations/emotions/Relieved_Sigh.fbx",
        motion:
          "Slightly raising shoulders and then falling into a relaxed pose",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "relief",
        key: "relief",
        useAsFallback: true,
        name: "Wiping Sweat",
        url: "aic-runtime-deps/animations/emotions/Wiping_Sweat.fbx",
        motion:
          "Wiping sweat off of the forehead while being in a side stance with slightly angled knees",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "relief",
        key: "relief",
        useAsFallback: true,
        name: "Exagerated Sigh",
        url: "aic-runtime-deps/animations/emotions/Shaking_It_Off.fbx",
        motion:
          "Taking a deep breath and slumping over into a loose, relaxed posture",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  remorse: {
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "remorse",
        key: "remorse",
        useAsFallback: true,
        name: "Praying",
        url: "aic-runtime-deps/animations/emotions/Praying.fbx",
        motion: "Praying on the knees",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  disappointment: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "disappointment",
        key: "disappointment",
        useAsFallback: true,
        name: "Pouting",
        url: "aic-runtime-deps/animations/emotions/Pouting.fbx",
        motion:
          "Slight head nod while slightly leaning forward with a very slightly angled posture",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "disappointment",
        key: "disappointment",
        useAsFallback: true,
        name: "Looking Down",
        url: "aic-runtime-deps/animations/emotions/Looking_Down.fbx",
        motion:
          "Looking down while slightly leaning forward with a very slightly angled posture",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "disappointment",
        key: "disappointment",
        useAsFallback: true,
        name: "Mild Head Shake",
        url: "aic-runtime-deps/animations/emotions/Light_Headshake_Talking.fbx",
        motion:
          "Lightly shaking the head and a tiny hand gesture, almost as to say 'bro...', but in the most subtle way",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "disappointment",
        key: "disappointment",
        useAsFallback: true,
        name: "Disappointed Head Shake",
        url: "aic-runtime-deps/animations/emotions/Golf_Putt_Failure.fbx",
        motion:
          "Shaking the head and looking to the side with arms to the hips",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "disappointment",
        key: "disappointment",
        useAsFallback: true,
        name: "'Damn' Gesture",
        url: "aic-runtime-deps/animations/emotions/Disappointed.fbx",
        motion:
          "Defeated swing-punch from the top-left to the bottom-right with a slight head shake while slightly leaning forward",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "disappointment",
        key: "disappointment",
        useAsFallback: true,
        name: "'God Damn' Gesture",
        url: "aic-runtime-deps/animations/emotions/Big_Disappointed.fbx",
        motion:
          "Very defeated swing-punch from the left and a slightly defeated swing-punch from the right with a slight head shake while slightly leaning forward",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
    ],
  },
  annoyance: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "annoyance",
        key: "annoyance",
        useAsFallback: true,
        name: "Looking Away",
        url: "aic-runtime-deps/animations/emotions/Look_Away_Gesture.fbx",
        motion:
          "Looking away in a dismissive manner, almost as to say 'whatever'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "annoyance",
        key: "annoyance",
        useAsFallback: false,
        name: "Slight Head Tilt",
        url: "aic-runtime-deps/animations/emotions/Thriller_Idle.fbx",
        motion:
          "head slightly tilted to the side wihlst in a wide stance, almost as to say 'b*tch please'",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "annoyance",
        key: "annoyance",
        useAsFallback: true,
        name: "Head Shake",
        url: "aic-runtime-deps/animations/emotions/Annoyed_Head_Shake.fbx",
        motion:
          "Head Shake with a wind up motion, almost like taking a breath and saying 'no'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "annoyance",
        key: "annoyance",
        useAsFallback: true,
        name: "Defeat",
        url: "aic-runtime-deps/animations/emotions/Defeated.fbx",
        motion:
          "Stomping down with one foot while throwing arms down in a defeated motion into a back-leaning posture",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "annoyance",
        key: "annoyance",
        useAsFallback: true,
        name: "Big Defeat",
        url: "aic-runtime-deps/animations/emotions/Defeat_Idle.fbx",
        motion:
          "Heavily stomping down with one foot while throwing arms down in a super defeated motion while slumping forward",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  gratitude: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "gratitude",
        key: "gratitude",
        useAsFallback: true,
        name: "Thankful",
        url: "aic-runtime-deps/animations/emotions/Thankful.fbx",
        motion: "Slight bow with one hand moving to the heart",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "gratitude",
        key: "gratitude",
        useAsFallback: false,
        name: "Quick Formal Bow",
        url: "aic-runtime-deps/animations/emotions/Quick_Formal_Bow.fbx",
        motion: "Quick bow with a small angle and a stiff stance",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "gratitude",
        key: "gratitude",
        useAsFallback: false,
        name: "Quick Bow",
        url: "aic-runtime-deps/animations/emotions/Quick_Informal_Bow.fbx",
        motion: "Quick bow with a slightly loose stance",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  approval: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "Reluctantly Agreeing",
        url: "aic-runtime-deps/animations/emotions/Agreeing.fbx",
        motion:
          "Raising the arms in front to mid-chest level with a slight head nod",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "Light Head Nod",
        url: "aic-runtime-deps/animations/emotions/Sarcastic_Head_Nod.fbx",
        motion: "Lightly nodding the head with a slight wind up time",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "Acknowledging",
        url: "aic-runtime-deps/animations/emotions/Acknowledging.fbx",
        motion: "Slight head nod, but in an assuring way",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "Light Nodding",
        url: "aic-runtime-deps/animations/emotions/Head_Nod_Yes.fbx",
        motion: "A confident, yet relaxed head nod",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "There You Go",
        url: "aic-runtime-deps/animations/emotions/Happy_Hand_Gesture.fbx",
        motion:
          "Slight head lean-back whilst doing an assuring hand gesture, almost as to say 'there you go'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "Hard Head Nod",
        url: "aic-runtime-deps/animations/emotions/Hard_Head_Nod.fbx",
        motion: "An abrupt, yet confident head nod",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "approval",
        key: "approval",
        useAsFallback: true,
        name: "Thumbs Up",
        url: "aic-runtime-deps/animations/emotions/Standing_Thumbs_Up.fbx",
        motion: "Confident thumbs up with a slight 'fist pump' motion",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  pride: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "pride",
        key: "pride",
        useAsFallback: true,
        name: "Head Turn",
        url: "aic-runtime-deps/animations/emotions/Cocky_Head_Turn.fbx",
        motion:
          "Turning the head to the side with a slide arm tilt to point the palm forward, almost as to say 'yeah, there you go'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "pride",
        key: "pride",
        useAsFallback: true,
        name: "Fist Pump",
        url: "aic-runtime-deps/animations/emotions/Fist_Pump.fbx",
        motion: "Slight fist pump at chest height",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "pride",
        key: "pride",
        useAsFallback: true,
        name: "Finger Guns",
        url: "aic-runtime-deps/animations/emotions/Pointing_Gesture.fbx",
        motion: "Both hands doing finger guns while slightly leaning back",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "pride",
        key: "pride",
        useAsFallback: true,
        name: "Being Cocky",
        url: "aic-runtime-deps/animations/emotions/Being_Cocky.fbx",
        motion:
          "Slight back lean with arms spreading low and palms pointing forward, almost as to say 'look at you!'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  neutral: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: false,
        name: "Neutral",
        url: "aic-runtime-deps/animations/emotions/Neutral.fbx",
        motion: "Idle posture",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Slight Head Turn",
        url: "aic-runtime-deps/animations/emotions/Head_Gesture.fbx",
        motion: "Slightly turning the head with minor hand movements",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: false,
        name: "Giving a Talk",
        url: "aic-runtime-deps/animations/emotions/Formal_Talking.fbx",
        motion: "Hands together while idling with slight head nods",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "formal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Slight Head Shake",
        url: "aic-runtime-deps/animations/emotions/Short_Talking.fbx",
        motion: "Slight head shaking with a double-handed talking gesture",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Light Breathing",
        url: "aic-runtime-deps/animations/emotions/Idle.fbx",
        motion: "Breathing lightly while swaying slightly from side to side",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Slight Turn Idle",
        url: "aic-runtime-deps/animations/emotions/Unarmed_Idle.fbx",
        motion:
          "Slight head turns while idling with arms in a lightly wide stance",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Slight Turn",
        url: "aic-runtime-deps/animations/emotions/Catwalk_Idle_Twist_R.fbx",
        motion: "Slight head turn while idling",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Talking",
        url: "aic-runtime-deps/animations/emotions/Talking.fbx",
        motion:
          "Slight head movements and hand gestures with a hand on the hip",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Hand Fanning",
        url: "aic-runtime-deps/animations/emotions/Dwarf_Idle.fbx",
        motion: "Idle head movements and posture while fanning air to the face",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Look Around",
        url: "aic-runtime-deps/animations/emotions/Idle_Look_Around.fbx",
        motion: "Looking at fingers and looking around",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "neutral",
        key: "neutral",
        useAsFallback: true,
        name: "Hand Gesture",
        url: "aic-runtime-deps/animations/emotions/Long_Talking.fbx",
        motion:
          "One hand on the hip while doing talking hand gestures with talking head motions",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
    ],
  },
  anger: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "anger",
        key: "anger",
        useAsFallback: true,
        name: "Heavy Breathing",
        url: "aic-runtime-deps/animations/emotions/Breathing_Idle.fbx",
        motion: "Slightly heavy breathing with a kind of tense posture",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "anger",
        key: "anger",
        useAsFallback: true,
        name: "Angry Gesture",
        url: "aic-runtime-deps/animations/emotions/Short_Angry_Gesture.fbx",
        motion: "Threatening head gesture while slightly leaning forward",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "anger",
        key: "anger",
        useAsFallback: true,
        name: "angry",
        url: "aic-runtime-deps/animations/emotions/Angry_Gesture.fbx",
        motion: "Punching down lightly with both hands with clenched fists",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "anger",
        key: "anger",
        useAsFallback: true,
        name: "Arguing",
        url: "aic-runtime-deps/animations/emotions/Standing_Arguing.fbx",
        motion:
          'Accusatory Hand Gestures that lead into a two handed gesture that kind of says "I can\'t believe you"',
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "anger",
        key: "anger",
        useAsFallback: true,
        name: "Shaking fist",
        url: "aic-runtime-deps/animations/emotions/Shake_Fist.fbx",
        motion: "Shaking one fist in the air",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "anger",
        key: "anger",
        useAsFallback: true,
        name: "Angry Talking",
        url: "aic-runtime-deps/animations/emotions/Angry_Talking.fbx",
        motion:
          "Intense hand and head gestures while idling with one hand on the hip",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
    ],
  },
  sadness: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "sadness",
        key: "sadness",
        useAsFallback: false,
        name: "Defeated Finger Snap",
        url: "aic-runtime-deps/animations/emotions/Small_Disappointed.fbx",
        motion:
          "Snapping fingers while swinging the right arm from right to left",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "sadness",
        key: "sadness",
        useAsFallback: false,
        name: "Light Shrug",
        url: "aic-runtime-deps/animations/emotions/Shrugging.fbx",
        motion: "Light shrugging motion with one shoulder",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "sadness",
        key: "sadness",
        useAsFallback: true,
        name: "Sad Stance",
        url: "aic-runtime-deps/animations/emotions/Sad_Idle.fbx",
        motion: "Slightly forward leaning posture while looking at the ground",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "sadness",
        key: "sadness",
        useAsFallback: true,
        name: "Sad Kick",
        url: "aic-runtime-deps/animations/emotions/Sad_Idle_Kick.fbx",
        motion:
          "Low-energy kick while leaning forward and looking at the ground",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "sadness",
        key: "sadness",
        useAsFallback: true,
        name: "Defeated Posture",
        url: "aic-runtime-deps/animations/emotions/Rejected.fbx",
        motion: "Slumping over and to the side while looking at the ground",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "sadness",
        key: "sadness",
        useAsFallback: true,
        name: "Crying",
        url: "aic-runtime-deps/animations/emotions/Defeat.fbx",
        motion:
          "Hands to the face while while looking at the ground and shaking the head",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  embarrassment: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "embarrassment",
        key: "embarrassment",
        useAsFallback: true,
        name: "Bashful Idle",
        url: "aic-runtime-deps/animations/emotions/Bashful.fbx",
        motion:
          "Lightly swaying from side to side while lightly kicking the ground with hands behind the back",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "embarrassment",
        key: "embarrassment",
        useAsFallback: true,
        name: "Cute Embarrassed",
        url: "aic-runtime-deps/animations/emotions/Crying.fbx",
        motion:
          "Slightly moving the head forward and back while holding hands to the face",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  curiosity: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "curiosity",
        key: "curiosity",
        useAsFallback: true,
        name: "Cute Thinking",
        url: "aic-runtime-deps/animations/emotions/Thinking.fbx",
        motion:
          "Hand to the chin with a hand on the hips while slighlty slanting to the side in a cute manner",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  joy: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "joy",
        key: "joy",
        useAsFallback: true,
        name: "Cute Swaying",
        url: "aic-runtime-deps/animations/emotions/Happy.fbx",
        motion: "Swaying from side to side and swinging arms in a cute manner",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "joy",
        key: "joy",
        useAsFallback: true,
        name: "Happy Idle",
        url: "aic-runtime-deps/animations/emotions/Happy_Idle.fbx",
        motion: "Happily swaying lightly from side to side",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "joy",
        key: "joy",
        useAsFallback: false,
        name: "Intense Clapping",
        url: "aic-runtime-deps/animations/emotions/Intense_Clapping.fbx",
        motion: "Clapping intensely",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "joy",
        key: "joy",
        useAsFallback: true,
        name: "Happy Jump",
        url: "aic-runtime-deps/animations/emotions/Joyful_Jump.fbx",
        motion:
          "Jumping in the air with elbows and knees angled and pals out and facing up",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  disapproval: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "disapproval",
        key: "disapproval",
        useAsFallback: true,
        name: "Wound-up Head Shake",
        url: "aic-runtime-deps/animations/emotions/Thoughtful_Head_Shake.fbx",
        motion:
          "Turning the head sideways and up and then shaking it lightly, almost as to say 'uhm..., no'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "disapproval",
        key: "disapproval",
        useAsFallback: true,
        name: "Finger Wagging",
        url: "aic-runtime-deps/animations/emotions/No.fbx",
        motion:
          "Wagging one finger at chest height with a streched out arm while slightly leaning forward, almost as to say 'nononono, uh-uh'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 2,
        metaType: "motion",
        emotion: "disapproval",
        key: "disapproval",
        useAsFallback: true,
        name: "Finger Point",
        url: "aic-runtime-deps/animations/emotions/Angry_Point.fbx",
        motion:
          "Pointing one finger down while leaning ever so slightly forward in a decisive manner, almost as to say 'stop that'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "disapproval",
        key: "disapproval",
        useAsFallback: true,
        name: "Definitive Rejection",
        url: "aic-runtime-deps/animations/emotions/Petting.fbx",
        motion:
          "Leaning sideways while moving the hand with an open palm forwards and backwards, kind of expressing 'I don't want anything to do with this'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 3,
        metaType: "motion",
        emotion: "disapproval",
        key: "disapproval",
        useAsFallback: true,
        name: "Emoted Finger Wagging",
        url: "aic-runtime-deps/animations/emotions/Big_No.fbx",
        motion:
          "Very emoted head shaking and finger wagging, almost as to say 'no, no, no, no, no. Never.'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  confusion: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "confusion",
        key: "confusion",
        useAsFallback: true,
        name: "Head Tilt",
        url: "aic-runtime-deps/animations/emotions/Neck_Stretching.fbx",
        motion: "Head tilting from side to side",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "confusion",
        key: "confusion",
        useAsFallback: true,
        name: "Whatever",
        url: "aic-runtime-deps/animations/emotions/Whatever_Gesture.fbx",
        motion:
          "Shrugging with a slight head tilt while doing a 'whatever' motion with both hands",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "confusion",
        key: "confusion",
        useAsFallback: true,
        name: "Confused Shrug",
        url: "aic-runtime-deps/animations/emotions/Confused_Shrugging.fbx",
        motion:
          "Shrugging while raising a hand to chest height with a flat palm, almost as to say 'f*ck if I know'",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "confusion",
        key: "confusion",
        useAsFallback: true,
        name: "Frantic Look Around",
        url: "aic-runtime-deps/animations/emotions/Looking_Around.fbx",
        motion: "Frantically looking around",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  fear: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "fear",
        key: "fear",
        useAsFallback: false,
        name: "Ready Stance",
        url: "aic-runtime-deps/animations/emotions/Fearful_Idle.fbx",
        motion: "Standing with legs in a side stance",
        motionType: "Loop",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "fear",
        key: "fear",
        useAsFallback: true,
        name: "Fearful Stance",
        url: "aic-runtime-deps/animations/emotions/Zombie_Idle.fbx",
        motion: "Wide stance hands at belly height, ready to take action",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    2: [
      {
        intensity: 2,
        metaType: "motion",
        emotion: "fear",
        key: "fear",
        useAsFallback: true,
        name: "Fearful",
        url: "aic-runtime-deps/animations/emotions/Look_Around.fbx",
        motion:
          "Looking around with arms angled slightly and a slight forward slouching postures",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "fear",
        key: "fear",
        useAsFallback: true,
        name: "Terrified",
        url: "aic-runtime-deps/animations/emotions/Terrified.fbx",
        motion:
          "Forward crouching with hands to the chest while looking side to side",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
  },
  excitement: {
    1: [
      {
        intensity: 1,
        metaType: "motion",
        emotion: "excitement",
        key: "excitement",
        useAsFallback: false,
        name: "Slow Talking",
        url: "aic-runtime-deps/animations/emotions/Slow_Speech_Talking.fbx",
        motion: "Emoted Arm Gestures in a talking motion",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
      {
        intensity: 1,
        metaType: "motion",
        emotion: "excitement",
        key: "excitement",
        useAsFallback: true,
        name: "Excited Hand Gesture",
        url: "aic-runtime-deps/animations/emotions/Hands_Forward_Gesture.fbx",
        motion: "Putting hands forwards together while slightly leaning back",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: false,
        motionSituation: "informal",
      },
    ],
    3: [
      {
        intensity: 3,
        metaType: "motion",
        emotion: "excitement",
        key: "excitement",
        useAsFallback: true,
        name: "Excited Talking",
        url: "aic-runtime-deps/animations/emotions/Excited_Talking.fbx",
        motion: "Doing intense arm and hand movements while talking",
        motionType: "Gesture",
        type: "fbx",
        onlyWhileTalking: true,
        motionSituation: "informal",
      },
    ],
  },
};
